services:
  db:
    image: postgres:17-alpine
    container_name: payload-plugin-cloudflare-purge-dev
    ports:
      - '30198:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
